#### Rodrigo Aguiar a22209738
#### Rafael Ramalhete a22209712
#### Mariana Carvalho a22001926

# Trabalho de avaliação 2

# Introdução 

Este trabalho é sobre o uso do algoritmo de **Hill Climbing** para resolver o famoso **Problema do Caixeiro Viajante** (Traveling Salesman Problem - **TSP**) de forma aproximada. O objetivo do **TSP** é encontrar o caminho mais curto que visita todas as cidades exatamente uma vez e retorna à cidade de origem.

# Bibliotecas
Estas linhas de código importam as bibliotecas **NumPy**, **Random** e **Networkx** para o ambiente Python.<br> 
O import **Random** traz uma caixa de ferramentas que nos ajuda a gerar números aleatórios. <br>
O import **NumPy** as np traz uma caixa de ferramentas que nos ajuda a lidar com matrizes e operações matemáticas. <br>
E o import **Networkx** as nx traz uma caixa de ferramentas que nos ajuda a trabalhar com grafos, que são maneiras de representar conexões entre coisas.

In [27]:
import random
import numpy as np
import networkx as nx

# Dados de entrada - Coordenadas das cidades

Neste bloco, são fornecidas as coordenadas das cidades. Cada linha da matriz representa as coordenadas (x, y) de uma cidade.

In [28]:
#coordinate of the points/cities
coordinate = np.array([[1,2], [30,21], [56,23], [8,18], [20,50], [3,4], [11,6], [6,7], [15,20], [10,9], [12,12]])

# Criação de uma matriz de adjacência

A função **'generate_matrix'** é responsável por calcular a matriz de adjacência para um grafo ponderado com base nas coordenadas fornecidas das cidades.
Inicialmente, é criada uma lista vazia chamada matrix para armazenar os valores das distâncias entre as cidades. De seguida, são usados dois loops **'for'** para percorrer todas as combinações possíveis de pares de cidades. O primeiro loop **'for'** itera todas as linhas da matriz coordinate, representando assim cada cidade, já o segundo loop **'for'** itera todas as colunas da matriz coordinate, novamente representando cada cidade. <br>
Para cada par de cidades representadas pelas coordenadas **'coordinate[i]'** e **'coordinate[j]'**, usamos a função **'np.linalg.norm()'** do **'NumPy'** para calcular a norma Euclidiana, ou seja, a distância euclidiana entre essas duas coordenadas(distância é a distância direta entre as duas cidades). Cada distância calculada é então adicionada à lista **'matrix'**. Após calcular todas as distâncias e armazená-las na lista matrix, é reestruturada em uma matriz bidimensional usando a função np.reshape().


In [29]:
#adjacency matrix for a weighted graph based on the given coordinates
def generate_matrix(coordinate):
    matrix = []
    for i in range(len(coordinate)):
        for j in range(len(coordinate)) :       
            p = np.linalg.norm(coordinate[i] - coordinate[j])
            matrix.append(p)
    matrix = np.reshape(matrix, (len(coordinate),len(coordinate)))
    np.set_printoptions(linewidth=160)
    print(matrix)
    return matrix

# Solução Random 
A função **'solution'** tem como objetivo encontrar uma solução inicial aleatória para o Problema do Caixeiro Viajante (TSP).<br>
É inicializada a lista **'points'** contendo os índices de todas as cidades, representadas por números de 0 a len(matrix) - 1, onde **'matrix'** é a matriz de adjacência do grafo.<br>
É feita uma iteração sobre o intervalo de 0 até o número de cidades no problema (o comprimento da matriz). Para cada iteração, é escolhido aleatoriamente um índice de cidade da lista **'points'** usando **'random.randint(0, len(points) - 1)'**(dá um índice aleatório dentro do intervalo de índices disponíveis). <br>
A cidade selecionada aleatoriamente é adicionada à lista **'solution'**, representando a ordem de visita das cidades. Em seguida, essa cidade é removida da lista **'points'** para garantir que não seja selecionada novamente. O loop continua até que todas as cidades tenham sido selecionadas e adicionadas à solução. Após selecionar aleatoriamente todas as cidades e adicioná-las à solução, é retornada a lista **'solution'**, que representa uma solução inicial aleatória para o TSP.

In [30]:
#finds a random solution    
def solution(matrix):
    points = list(range(0, len(matrix)))
    solution = []
    for i in range(0, len(matrix)):
        random_point = points[random.randint(0, len(points) - 1)]
        solution.append(random_point)
        points.remove(random_point)
    return solution

# Cálculo do comprimento do caminho
A função **'path_length'** é responsável por calcular o comprimento total do caminho para uma solução dada do Problema do Caixeiro Viajante (TSP). A variável cycle_length é inicializada com o valor zero e será usada para armazenar o comprimento total do ciclo, que representa o caminho percorrido pelo caixeiro viajante.<br>
É realizada uma iteração sobre os índices da lista **'solution'**, que contém a ordem em que as cidades devem ser visitadas. Para cada cidade na solução, somamos à variável **'cycle_length'** a distância entre a cidade atual e a cidade anterior na solução. Essa distância é obtida consultando a matriz de adjacência matrix nas posições **'[solution[i]][solution[i - 1]]'**.<br>
Após percorrer todas as cidades na solução e somar as distâncias entre elas, retornamos o valor final de **'cycle_length'**, que representa o comprimento total do caminho percorrido pelo caixeiro viajante.

In [31]:
#calculate the path based on the random solution
def path_length(matrix, solution):
    cycle_length = 0
    for i in range(0, len(solution)):
        cycle_length += matrix[solution[i]][solution[i - 1]]
    return cycle_length

# Gereção de vizinhos 
A função **'neighbors'** é responsável por gerar os vizinhos da solução atual, trocando as cidades na solução, e retorna o melhor vizinho encontrado.<br>
A lista **'neighbors'** é inicializada como uma lista vazia, que será preenchida com as soluções vizinhas.<br>
Percorremos todas as combinações possíveis de pares de cidades na solução atual com o primeiro loop que itera sobre os índices de todas as cidades na solução. Começamos um segundo loop que itera sobre os índices de todas as cidades na solução, começando de **'i + 1'**, garantindo que não existem trocas de uma cidade por ela mesma.<br>
Adicionamos o vizinho gerado à lista **'neighbors'**. Assumimos que o primeiro vizinho na lista de vizinhos é o melhor vizinho inicialmente. Isso é feito atribuindo **'best_neighbor'** como o primeiro vizinho na lista e calculando o custo desse vizinho usando a função **'path_length'**.<br>
Para cada vizinho, calculamos o custo (comprimento do caminho) utilizando a função **'path_length'**. Se o custo do vizinho atual for menor que o custo do melhor vizinho encontrado até agora, atualizamos o melhor vizinho e o melhor custo.<br>
Após percorrer todos os vizinhos e encontrar o melhor, retornamos o melhor vizinho e seu custo.


In [32]:
#generate neighbors of the random solution by swapping cities and returns the best neighbor
def neighbors(matrix, solution):
    neighbors = []
    for i in range(len(solution)):
        for j in range(i + 1, len(solution)):
            neighbor = solution.copy()
            neighbor[i] = solution[j]
            neighbor[j] = solution[i]
            neighbors.append(neighbor)
             
    #assume that the first neighbor in the list is the best neighbor      
    best_neighbor = neighbors[0]
    best_path = path_length(matrix, best_neighbor)
     
    #check if there is a better neighbor
    for neighbor in neighbors:
        current_path = path_length(matrix, neighbor)
        if current_path < best_path:
            best_path = current_path
            best_neighbor = neighbor
    return best_neighbor, best_path

# Escolha do melhor vizinho 

A função **'hill_climbing'** implementa o algoritmo de **'Hill Climbing'** para resolver o Problema do Caixeiro Viajante (**'TSP'**).<br>
É usada a função **'generate_matrix(coordinate)'** para gerar a matriz de adjacência com base nas coordenadas das cidades fornecidas. É tambem usada a função **'solution(matrix)'** para obter uma solução inicial aleatória para o **'TSP'**. <br>
É emtão calculado o custo (comprimento do caminho) da solução atual utilizando a função **'path_length(matrix, current_solution)'**.A função **'neighbors(matrix, current_solution)'** para obter o melhor vizinho da solução atual. O melhor vizinho é aquele com o menor custo. De seguida é inciado um loop while que continua enquanto o custo do melhor vizinho encontrado for menor que o custo da solução atual. Dentro do loop, atualizamos a solução atual e seu custo para serem iguais ao melhor vizinho encontrado. Em seguida, buscamos o melhor vizinho da nova solução e repetimos o processo.<br>
Quando não há mais melhorias possíveis, saímos do loop e retornamos a solução final encontrada, representada pelo comprimento do caminho (current_path) e a ordem das cidades visitadas (current_solution).


In [33]:
def hill_climbing(coordinate):
    matrix = generate_matrix(coordinate)
     
    current_solution = solution(matrix)
    current_path = path_length(matrix, current_solution)
    neighbor = neighbors(matrix,current_solution)[0]
    best_neighbor, best_neighbor_path = neighbors(matrix, neighbor)
 
    while best_neighbor_path < current_path:
        print ("best = ", best_neighbor)
        print ("best_path = ", best_neighbor_path)
        current_solution = best_neighbor
        current_path = best_neighbor_path
        neighbor = neighbors(matrix, current_solution)[0]
        best_neighbor, best_neighbor_path = neighbors(matrix, neighbor)
 
    return current_path, current_solution

# Chamada da função principal e impressão da solução final

Este bloco de código executa o algoritmo de Hill Climbing para resolver o Problema do Caixeiro Viajante (TSP) com base nas coordenadas das cidades fornecidas. Em seguida, imprime a solução final na tela, que consiste no caminho mais curto encontrado e oseu comprimento total. **uma vez que o algoritmo está a apresentar  cada vez mais um melhor caminho podemos considerar bem**

In [34]:
final_solution = hill_climbing(coordinate)
print("The solution is \n", final_solution[1])

[[ 0.         34.66987165 58.87274412 17.4642492  51.623638    2.82842712 10.77032961  7.07106781 22.8035085  11.40175425 14.86606875]
 [34.66987165  0.         26.07680962 22.20360331 30.6757233  31.90611227 24.20743687 27.78488798 15.03329638 23.32380758 20.1246118 ]
 [58.87274412 26.07680962  0.         48.25971405 45.         56.30275304 48.10405388 52.49761899 41.10960958 48.08326112 45.35416188]
 [17.4642492  22.20360331 48.25971405  0.         34.17601498 14.86606875 12.36931688 11.18033989  7.28010989  9.21954446  7.21110255]
 [51.623638   30.6757233  45.         34.17601498  0.         49.04079934 44.91102315 45.22167622 30.41381265 42.20189569 38.83297568]
 [ 2.82842712 31.90611227 56.30275304 14.86606875 49.04079934  0.          8.24621125  4.24264069 20.          8.60232527 12.04159458]
 [10.77032961 24.20743687 48.10405388 12.36931688 44.91102315  8.24621125  0.          5.09901951 14.56021978  3.16227766  6.08276253]
 [ 7.07106781 27.78488798 52.49761899 11.18033989 45.22

# Teste

Para testar o algoritmo de Hill Climbing, criámos um conjunto de coordenadas de cidades e observámos a solução final encontrada. Este código irá executar o algoritmo de Hill Climbing com as coordenadas fornecidas e imprimir a ordem das cidades visitadas na solução final.

In [35]:
test_coordinates = np.array([[0, 0], [1, 1], [2, 2], [3, 3], [4, 4]])
final_solution = hill_climbing(test_coordinates)
print("A solução final é:\n", final_solution[1])

[[0.         1.41421356 2.82842712 4.24264069 5.65685425]
 [1.41421356 0.         1.41421356 2.82842712 4.24264069]
 [2.82842712 1.41421356 0.         1.41421356 2.82842712]
 [4.24264069 2.82842712 1.41421356 0.         1.41421356]
 [5.65685425 4.24264069 2.82842712 1.41421356 0.        ]]
best =  [1, 4, 3, 2, 0]
best_path =  11.31370849898476
A solução final é:
 [1, 4, 3, 2, 0]


# Variantes:

# 1. Estocástico

Para implementar a variante estocástica do algoritmo de Hill Climbing, é que introduzimos a função **random_neighbor**, que gera um vizinho aleatório trocando aleatoriamente duas cidades na solução atual. Na função **stochastic_hill_climbing**, iteramos por um número máximo de iterações, gerando um vizinho aleatório em cada iteração e, às vezes, aceitando vizinhos piores com uma certa probabilidade (random.random() < 0.5). 
A principal diferença é que, em vez de escolher sempre o melhor vizinho, agora escolhemos um vizinho aleatório com uma certa probabilidade, mesmo que esta seja pior do que a solução atual. Isso ajuda a evitar ficar preso em ótimos locais locais.

In [36]:
def random_neighbor(matrix, solution):
    i, j = random.sample(range(len(solution)), 2)
    neighbor = solution.copy()
    neighbor[i] = solution[j]
    neighbor[j] = solution[i]
    return neighbor

def stochastic_hill_climbing(coordinate, max_iterations=1000):
    matrix = generate_matrix(coordinate)

    current_solution = solution(matrix)
    current_path = path_length(matrix, current_solution)

    for _ in range(max_iterations):
        neighbor = random_neighbor(matrix, current_solution)
        neighbor_path = path_length(matrix, neighbor)

        if neighbor_path < current_path or random.random() < 0.5:  
            current_solution = neighbor
            current_path = neighbor_path

    return current_path, current_solution


In [37]:
final_solution = stochastic_hill_climbing(coordinate)
print("The solution is \n", final_solution[1])

[[ 0.         34.66987165 58.87274412 17.4642492  51.623638    2.82842712 10.77032961  7.07106781 22.8035085  11.40175425 14.86606875]
 [34.66987165  0.         26.07680962 22.20360331 30.6757233  31.90611227 24.20743687 27.78488798 15.03329638 23.32380758 20.1246118 ]
 [58.87274412 26.07680962  0.         48.25971405 45.         56.30275304 48.10405388 52.49761899 41.10960958 48.08326112 45.35416188]
 [17.4642492  22.20360331 48.25971405  0.         34.17601498 14.86606875 12.36931688 11.18033989  7.28010989  9.21954446  7.21110255]
 [51.623638   30.6757233  45.         34.17601498  0.         49.04079934 44.91102315 45.22167622 30.41381265 42.20189569 38.83297568]
 [ 2.82842712 31.90611227 56.30275304 14.86606875 49.04079934  0.          8.24621125  4.24264069 20.          8.60232527 12.04159458]
 [10.77032961 24.20743687 48.10405388 12.36931688 44.91102315  8.24621125  0.          5.09901951 14.56021978  3.16227766  6.08276253]
 [ 7.07106781 27.78488798 52.49761899 11.18033989 45.22

# 2. Primeiro-melhor

Para implementar a variante **primeiro-melhor** do algoritmo de Hill Climbing, faremos uma alteração na função **neighbors** para gerar apenas um vizinho por iteração e aceitar esse vizinho imediatamente se ele for melhor que a solução atual. Nesta versão da função **neighbors**, iteramos sobre todos os vizinhos, mas assim que encontramos o primeiro vizinho cujo caminho é melhor que o da solução atual, retornamos esse vizinho. Se nenhum vizinho for melhor, retornamos a solução atual. <br>
A função **'first_best_hill_climbing'** retorna quando um vizinho melhor é encontrado. Se nenhum vizinho melhor for encontrado após o número máximo de iterações, a solução atual é retornada, garantido assim que escolhemos sempre a primeira solução melhor que a atual que encontramos durante a procura.

In [38]:
def random_neighbor(matrix, solution):
    i, j = random.sample(range(len(solution)), 2)
    neighbor = solution.copy()
    neighbor[i] = solution[j]
    neighbor[j] = solution[i]
    return neighbor

def first_best_hill_climbing(coordinate, max_iterations=1000):
    matrix = generate_matrix(coordinate)

    current_solution = solution(matrix)
    current_path = path_length(matrix, current_solution)

    for _ in range(max_iterations):
        neighbor = random_neighbor(matrix, current_solution)
        neighbor_path = path_length(matrix, neighbor)

        if neighbor_path < current_path:
            return neighbor_path, neighbor  # Return first better neighbor found

    return current_path, current_solution  # If no better neighbor is found, return current solution



In [39]:
final_solution = first_best_hill_climbing(coordinate)
print("The solution is \n", final_solution[1])

[[ 0.         34.66987165 58.87274412 17.4642492  51.623638    2.82842712 10.77032961  7.07106781 22.8035085  11.40175425 14.86606875]
 [34.66987165  0.         26.07680962 22.20360331 30.6757233  31.90611227 24.20743687 27.78488798 15.03329638 23.32380758 20.1246118 ]
 [58.87274412 26.07680962  0.         48.25971405 45.         56.30275304 48.10405388 52.49761899 41.10960958 48.08326112 45.35416188]
 [17.4642492  22.20360331 48.25971405  0.         34.17601498 14.86606875 12.36931688 11.18033989  7.28010989  9.21954446  7.21110255]
 [51.623638   30.6757233  45.         34.17601498  0.         49.04079934 44.91102315 45.22167622 30.41381265 42.20189569 38.83297568]
 [ 2.82842712 31.90611227 56.30275304 14.86606875 49.04079934  0.          8.24621125  4.24264069 20.          8.60232527 12.04159458]
 [10.77032961 24.20743687 48.10405388 12.36931688 44.91102315  8.24621125  0.          5.09901951 14.56021978  3.16227766  6.08276253]
 [ 7.07106781 27.78488798 52.49761899 11.18033989 45.22

# 3. Reinicialização aleatória
Para implementar a variante de **reinicialização aleatória** do algoritmo de Hill Climbing, podemos adicionar um critério de reinicialização que reinicia o processo de busca com uma nova solução aleatória sempre que uma quantidade específica de iterações não melhorar a solução atual. Vamos introduzir um parâmetro **restart_threshold** na função **hill_climbing**, que determinará quantas iterações devem ocorrer sem melhoria antes de reiniciar com uma nova solução aleatória. Quando o número de iterações sem melhoria atingir o limite especificado, reiniciaremos o processo com uma nova solução aleatória e zeraremos o contador de iterações.<br>
Adicionámos a variável **iterations_without_improvement** para rastrear o número de iterações consecutivas sem melhoria. Quando esse número atinge ou ultrapassa o limiar definido em **restart_threshold**, reinicializamos a procura a partir de uma nova solução aleatória. Isso ajuda a evitar que o algoritmo fique preso em ótimos locais, permitindo que explore diferentes partes do espaço de solução.

In [40]:
def random_restart_hill_climbing(coordinate, max_iterations=1000, restart_threshold=100):
    matrix = generate_matrix(coordinate)
    current_solution = solution(matrix)
    current_path = path_length(matrix, current_solution)
    iterations_without_improvement = 0

    for _ in range(max_iterations):
        neighbor = random_neighbor(matrix, current_solution)
        neighbor_path = path_length(matrix, neighbor)

        if neighbor_path < current_path:
            current_solution = neighbor
            current_path = neighbor_path
            iterations_without_improvement = 0
        else:
            iterations_without_improvement += 1

        if iterations_without_improvement >= restart_threshold:
            current_solution = solution(matrix)  # Random restart
            current_path = path_length(matrix, current_solution)
            iterations_without_improvement = 0

    return current_path, current_solution

In [41]:
final_solution = random_restart_hill_climbing(coordinate)
print("The solution is \n", final_solution[1])

[[ 0.         34.66987165 58.87274412 17.4642492  51.623638    2.82842712 10.77032961  7.07106781 22.8035085  11.40175425 14.86606875]
 [34.66987165  0.         26.07680962 22.20360331 30.6757233  31.90611227 24.20743687 27.78488798 15.03329638 23.32380758 20.1246118 ]
 [58.87274412 26.07680962  0.         48.25971405 45.         56.30275304 48.10405388 52.49761899 41.10960958 48.08326112 45.35416188]
 [17.4642492  22.20360331 48.25971405  0.         34.17601498 14.86606875 12.36931688 11.18033989  7.28010989  9.21954446  7.21110255]
 [51.623638   30.6757233  45.         34.17601498  0.         49.04079934 44.91102315 45.22167622 30.41381265 42.20189569 38.83297568]
 [ 2.82842712 31.90611227 56.30275304 14.86606875 49.04079934  0.          8.24621125  4.24264069 20.          8.60232527 12.04159458]
 [10.77032961 24.20743687 48.10405388 12.36931688 44.91102315  8.24621125  0.          5.09901951 14.56021978  3.16227766  6.08276253]
 [ 7.07106781 27.78488798 52.49761899 11.18033989 45.22

#  Contar número de soluções geradas em cada variante, incluindo a tradicional.

Para contar o número de soluções geradas em cada variante do algoritmo de Hill Climbing, iremos usar a função **'path_lengt´** modificada de modo a não só calcular o comprimento do ciclo para uma dada solução, mas também manter o controlo do número de vezes que é chamada, permitindo que se saiba quantas vezes o comprimento do caminho foi calculado ao longo do tempo, isto através do contador implementado na função.

In [42]:
def path_length(matrix, solution, counter):
    counter[0] += 1
    cycle_length = 0
    for i in range(len(solution)):
        cycle_length += matrix[solution[i]][solution[i - 1]]
    return cycle_length

Vamos alterar as diferentes variantes de modo a introduzir o counter nas mesmas. <br>

# Tradicional hill climbing

In [43]:
def hill_climbing(coordinate, max_iterations=1000):
    matrix = generate_matrix(coordinate)
    counter = [0]
    current_solution = solution(matrix)
    current_path = path_length(matrix, current_solution, counter)

    for _ in range(max_iterations):
        neighbor = random_neighbor(matrix, current_solution)
        neighbor_path = path_length(matrix, neighbor, counter)

        if neighbor_path < current_path:
            current_solution = neighbor
            current_path = neighbor_path

    return current_path, current_solution, counter[0]

traditional_solution = hill_climbing(coordinate)

[[ 0.         34.66987165 58.87274412 17.4642492  51.623638    2.82842712 10.77032961  7.07106781 22.8035085  11.40175425 14.86606875]
 [34.66987165  0.         26.07680962 22.20360331 30.6757233  31.90611227 24.20743687 27.78488798 15.03329638 23.32380758 20.1246118 ]
 [58.87274412 26.07680962  0.         48.25971405 45.         56.30275304 48.10405388 52.49761899 41.10960958 48.08326112 45.35416188]
 [17.4642492  22.20360331 48.25971405  0.         34.17601498 14.86606875 12.36931688 11.18033989  7.28010989  9.21954446  7.21110255]
 [51.623638   30.6757233  45.         34.17601498  0.         49.04079934 44.91102315 45.22167622 30.41381265 42.20189569 38.83297568]
 [ 2.82842712 31.90611227 56.30275304 14.86606875 49.04079934  0.          8.24621125  4.24264069 20.          8.60232527 12.04159458]
 [10.77032961 24.20743687 48.10405388 12.36931688 44.91102315  8.24621125  0.          5.09901951 14.56021978  3.16227766  6.08276253]
 [ 7.07106781 27.78488798 52.49761899 11.18033989 45.22

#  Estocástico

In [44]:
def stochastic_hill_climbing(coordinate, max_iterations=1000):
    matrix = generate_matrix(coordinate)
    counter = [0]
    current_solution = solution(matrix)
    current_path = path_length(matrix, current_solution, counter)

    for _ in range(max_iterations):
        neighbor = random_neighbor(matrix, current_solution)
        neighbor_path = path_length(matrix, neighbor, counter)

        if neighbor_path < current_path or random.random() < 0.5:
            current_solution = neighbor
            current_path = neighbor_path

    return current_path, current_solution, counter[0]

stochastic_solution = stochastic_hill_climbing(coordinate)

[[ 0.         34.66987165 58.87274412 17.4642492  51.623638    2.82842712 10.77032961  7.07106781 22.8035085  11.40175425 14.86606875]
 [34.66987165  0.         26.07680962 22.20360331 30.6757233  31.90611227 24.20743687 27.78488798 15.03329638 23.32380758 20.1246118 ]
 [58.87274412 26.07680962  0.         48.25971405 45.         56.30275304 48.10405388 52.49761899 41.10960958 48.08326112 45.35416188]
 [17.4642492  22.20360331 48.25971405  0.         34.17601498 14.86606875 12.36931688 11.18033989  7.28010989  9.21954446  7.21110255]
 [51.623638   30.6757233  45.         34.17601498  0.         49.04079934 44.91102315 45.22167622 30.41381265 42.20189569 38.83297568]
 [ 2.82842712 31.90611227 56.30275304 14.86606875 49.04079934  0.          8.24621125  4.24264069 20.          8.60232527 12.04159458]
 [10.77032961 24.20743687 48.10405388 12.36931688 44.91102315  8.24621125  0.          5.09901951 14.56021978  3.16227766  6.08276253]
 [ 7.07106781 27.78488798 52.49761899 11.18033989 45.22

# Primeiro-melhor

In [45]:
def first_best_hill_climbing(coordinate, max_iterations=1000):
    matrix = generate_matrix(coordinate)
    counter = [0]
    current_solution = solution(matrix)
    current_path = path_length(matrix, current_solution, counter)

    for _ in range(max_iterations):
        neighbor = random_neighbor(matrix, current_solution)
        neighbor_path = path_length(matrix, neighbor, counter)

        if neighbor_path < current_path:
            return neighbor_path, neighbor, counter[0]

    return current_path, current_solution, counter[0]

first_best_solution = first_best_hill_climbing(coordinate)

[[ 0.         34.66987165 58.87274412 17.4642492  51.623638    2.82842712 10.77032961  7.07106781 22.8035085  11.40175425 14.86606875]
 [34.66987165  0.         26.07680962 22.20360331 30.6757233  31.90611227 24.20743687 27.78488798 15.03329638 23.32380758 20.1246118 ]
 [58.87274412 26.07680962  0.         48.25971405 45.         56.30275304 48.10405388 52.49761899 41.10960958 48.08326112 45.35416188]
 [17.4642492  22.20360331 48.25971405  0.         34.17601498 14.86606875 12.36931688 11.18033989  7.28010989  9.21954446  7.21110255]
 [51.623638   30.6757233  45.         34.17601498  0.         49.04079934 44.91102315 45.22167622 30.41381265 42.20189569 38.83297568]
 [ 2.82842712 31.90611227 56.30275304 14.86606875 49.04079934  0.          8.24621125  4.24264069 20.          8.60232527 12.04159458]
 [10.77032961 24.20743687 48.10405388 12.36931688 44.91102315  8.24621125  0.          5.09901951 14.56021978  3.16227766  6.08276253]
 [ 7.07106781 27.78488798 52.49761899 11.18033989 45.22

#  Reinicialização aleatória

In [46]:
def random_restart_hill_climbing(coordinate, max_iterations=1000, restart_threshold=100):
    matrix = generate_matrix(coordinate)
    counter = [0]
    current_solution = solution(matrix)
    current_path = path_length(matrix, current_solution, counter)
    iterations_without_improvement = 0

    for _ in range(max_iterations):
        neighbor = random_neighbor(matrix, current_solution)
        neighbor_path = path_length(matrix, neighbor, counter)

        if neighbor_path < current_path:
            current_solution = neighbor
            current_path = neighbor_path
            iterations_without_improvement = 0
        else:
            iterations_without_improvement += 1

        if iterations_without_improvement >= restart_threshold:
            current_solution = solution(matrix) 
            current_path = path_length(matrix, current_solution, counter)
            iterations_without_improvement = 0

    return current_path, current_solution, counter[0]

random_restart_solution = random_restart_hill_climbing(coordinate)

[[ 0.         34.66987165 58.87274412 17.4642492  51.623638    2.82842712 10.77032961  7.07106781 22.8035085  11.40175425 14.86606875]
 [34.66987165  0.         26.07680962 22.20360331 30.6757233  31.90611227 24.20743687 27.78488798 15.03329638 23.32380758 20.1246118 ]
 [58.87274412 26.07680962  0.         48.25971405 45.         56.30275304 48.10405388 52.49761899 41.10960958 48.08326112 45.35416188]
 [17.4642492  22.20360331 48.25971405  0.         34.17601498 14.86606875 12.36931688 11.18033989  7.28010989  9.21954446  7.21110255]
 [51.623638   30.6757233  45.         34.17601498  0.         49.04079934 44.91102315 45.22167622 30.41381265 42.20189569 38.83297568]
 [ 2.82842712 31.90611227 56.30275304 14.86606875 49.04079934  0.          8.24621125  4.24264069 20.          8.60232527 12.04159458]
 [10.77032961 24.20743687 48.10405388 12.36931688 44.91102315  8.24621125  0.          5.09901951 14.56021978  3.16227766  6.08276253]
 [ 7.07106781 27.78488798 52.49761899 11.18033989 45.22

Iremos então chamar as diferentes variantes e analisar os resultados.

In [47]:
print("Solução do Hill Climbing Tradicional: ", traditional_solution[0])
print("Número de soluções geradas no Hill Climbing Tradicional: ", traditional_solution[2], "\n")

print("Solução do Hill Climbing Estocástico: ", stochastic_solution[0])
print("Número de soluções geradas no Hill Climbing Estocástico: ", stochastic_solution[2], "\n")

print("Solução do Hill Climbing Primeiro-Melhor: ", first_best_solution[0])
print("Número de soluções geradas no Hill Climbing Primeiro-Melhor: ", first_best_solution[2], "\n")

print("Solução do Hill Climbing Reinicialização Aleatória: ", random_restart_solution[0])
print("Número de soluções geradas no Hill Climbing Reinicialização Aleatória: ", random_restart_solution[2], "\n")


Solução do Hill Climbing Tradicional:  164.61969097503695
Número de soluções geradas no Hill Climbing Tradicional:  1001 

Solução do Hill Climbing Estocástico:  242.4087100914783
Número de soluções geradas no Hill Climbing Estocástico:  1001 

Solução do Hill Climbing Primeiro-Melhor:  212.27158187912124
Número de soluções geradas no Hill Climbing Primeiro-Melhor:  3 

Solução do Hill Climbing Reinicialização Aleatória:  218.3084753407551
Número de soluções geradas no Hill Climbing Reinicialização Aleatória:  1005 



Com base nos resultados fornecidos, podemos observar o número de soluções geradas por cada variante em diferentes instâncias do problema e dizer que:
* O **Hill Climbing Tradicional** e o **Estocástico** geraram um número igual de soluções, ambos ultrapassando o limite de 1000 iterações, o que indica que podem ter dificuldade em encontrar uma solução ideal para este problema específico dentro desse limite.
* O **Hill Climbing Primeiro-Melhor** obteve uma solução comparável aos outros métodos, mas gerou significativamente menos soluções (apenas 6), indicando que pode ser mais eficiente em termos de procura, uma vez que pára assim que encontra uma solução que melhora.
* O **Hill Climbing Reinicialização Aleatória** gerou um número maior de soluções do que os outros métodos. Embora tenha alcançado uma solução semelhante à do **Hill Climbing Tradicional**, a abordagem de reinicialização aleatória pode levar a uma exploração mais ampla do espaço de soluções, potencialmente resultando em melhores soluções em problemas complexos. No entanto, isso também pode aumentar o tempo de execução.


# Definir, implementar e testar outra regra de vizinhança local.

Uma outra regra de vizinhança local que podemos implementar é a troca de três cidades consecutivas. Esta regra implica trocar a posição de três cidades consecutivas na solução atual.

In [48]:
def neighbor_swap_three(matrix, solution):
    n = len(solution)
    i = random.randint(0, n - 3)
    j = i + 1
    k = i + 2
    neighbor = solution.copy()
    neighbor[i], neighbor[j], neighbor[k] = solution[k], solution[i], solution[j]
    return neighbor


Modificação a função hill_climbing para utilizar essa nova regra de vizinhança.

In [49]:
def traditional_hill_climbing_swap_three(coordinate, max_iterations=1000):
    matrix = generate_matrix(coordinate)
    counter = [0]
    current_solution = solution(matrix)
    current_path = path_length(matrix, current_solution, counter)

    for _ in range(max_iterations):
        neighbor = neighbor_swap_three(matrix, current_solution)
        neighbor_path = path_length(matrix, neighbor, counter)

        if neighbor_path < current_path:
            current_solution = neighbor
            current_path = neighbor_path
        else:
            break

    return current_path, current_solution, counter[0]


Testes

In [50]:
traditional_solution = traditional_hill_climbing_swap_three(coordinate)
print("Solução do Hill Climbing Tradicional (Troca de Três): ", traditional_solution[0])
print("Número de soluções geradas no Hill Climbing Tradicional (Troca de Três): ", traditional_solution[2], "\n")

[[ 0.         34.66987165 58.87274412 17.4642492  51.623638    2.82842712 10.77032961  7.07106781 22.8035085  11.40175425 14.86606875]
 [34.66987165  0.         26.07680962 22.20360331 30.6757233  31.90611227 24.20743687 27.78488798 15.03329638 23.32380758 20.1246118 ]
 [58.87274412 26.07680962  0.         48.25971405 45.         56.30275304 48.10405388 52.49761899 41.10960958 48.08326112 45.35416188]
 [17.4642492  22.20360331 48.25971405  0.         34.17601498 14.86606875 12.36931688 11.18033989  7.28010989  9.21954446  7.21110255]
 [51.623638   30.6757233  45.         34.17601498  0.         49.04079934 44.91102315 45.22167622 30.41381265 42.20189569 38.83297568]
 [ 2.82842712 31.90611227 56.30275304 14.86606875 49.04079934  0.          8.24621125  4.24264069 20.          8.60232527 12.04159458]
 [10.77032961 24.20743687 48.10405388 12.36931688 44.91102315  8.24621125  0.          5.09901951 14.56021978  3.16227766  6.08276253]
 [ 7.07106781 27.78488798 52.49761899 11.18033989 45.22

Comparando com as restantes variávies:
* A nova regra de vizinhança de **troca de três** obteve uma solução com um custo significativamente maior em comparação com todas as outras variantes, exceto a Reinicialização Aleatória. Além disso, gerou um número muito menor de soluções, sugerindo que pode ter ficado preso em um ótimo local. 
* Não conseguiu superar a solução encontrada pelo **Hill Climbing Tradicional**, nem mesmo se aproximou das soluções encontradas pelo **Hill Climbing Estocástico**, **Primeiro-Melhor** e **Reinicialização Aleatória**. Isso indica que essa nova regra pode não ser eficaz para este problema específico.
* Em geral, os resultados sugerem que a nova regra de vizinhança de **troca de três** não melhorou significativamente o desempenho do **Hill Climbing Tradicional** para este problema. Seria necessário avaliar mais a fundo o comportamento dessa nova regra em diferentes cenários e talvez ajustar seus parâmetros para obter melhores resultados.